//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Contabilidad.Models
{
    public partial class Categoria
    {
        public Categoria()
        {
            this.Empleadoes = new HashSet<Empleado>();
        }
    
        public int CategoriaID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Empleado> Empleadoes { get; set; }
    }
}
