//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Contabilidad.Models
{
    public partial class GarCasEntities : DbContext
    {
        public GarCasEntities()
            : base("name=GarCasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<ObraSocial> ObraSocials { get; set; }
        public virtual DbSet<Sindicato> Sindicatoes { get; set; }
        public virtual DbSet<UsuarioSistema> UsuarioSistemas { get; set; }
        public virtual DbSet<UsuarioSistemaEmpresa> UsuarioSistemaEmpresas { get; set; }
    }
}
