//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Contabilidad.Models
{
    public partial class Empleado
    {
        public int EmpresaID { get; set; }
        public int EmpleadoID { get; set; }
        public string Legajo { get; set; }
        public string Nombre { get; set; }
        public string CUIL { get; set; }
        public Nullable<DateTime> FechaIngreso { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> EstadoCivilID { get; set; }
        public Nullable<int> ObraSocialID { get; set; }
        public bool TieneConyuge { get; set; }
        public bool TieneHijos { get; set; }
        public bool TieneOtrasCargas { get; set; }
        public bool TienePrimasSeguro { get; set; }
        public bool TieneGastosSepelio { get; set; }
        public Nullable<int> SindicatoID { get; set; }
        public bool EstaAfiliado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ObraSocial ObraSocial { get; set; }
        public virtual Sindicato Sindicato { get; set; }
    }
}
