//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Contabilidad.Models
{
    public partial class Empresa
    {
        public int EmpresaID { get; set; }
        public string Nombre { get; set; }
        public byte[] Logo { get; set; }
        public string Domicilio { get; set; }
        public string CUIT { get; set; }
        public Nullable<int> BancoID { get; set; }
        public Nullable<DateTime> FechaUltimoDeposito { get; set; }
    
        public virtual Banco Banco { get; set; }
    }
}
