//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Contabilidad.Models
{
    public partial class Sindicato
    {
        public Sindicato()
        {
            this.Empleadoes = new HashSet<Empleado>();
        }
    
        public int SindicatoID { get; set; }
        public string SindicatoCodigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PorcentajeAfiliado { get; set; }
        public Nullable<decimal> PorcentajeNoAfiliado { get; set; }
        public Nullable<decimal> SeguroSepelioAfiliado { get; set; }
        public Nullable<decimal> SeguroSepelioNoAfiliado { get; set; }
    
        public virtual ICollection<Empleado> Empleadoes { get; set; }
    }
}
