//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contabilidad.Models
{
    public partial class UsuarioSistema
    {
        public int UsuarioID { get; set; }
        public string Nombre { get; set; }
        public bool EstaActivo { get; set; }
    }
}
